name: Zig Package Release

on:
  release:
    types: [published]

jobs:
  zig-release:
    if: startsWith(github.ref, 'refs/tags/zig-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Zig package
        run: |
          mkdir zig-package
          cp -r implementations/wasm-zig/* zig-package/
          cd zig-package
          tar --transform='s|^\./||' -czf ../zaw-wasm.tar.gz .

      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./zaw-wasm.tar.gz
          asset_name: zaw-wasm.tar.gz
          asset_content_type: application/gzip
